# Generated by Django 4.1 on 2022-11-24 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginwebsite', '0002_user_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dateCreated',
        ),
    ]
