# Generated by Django 4.1 on 2022-11-24 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginwebsite', '0005_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='session_id',
        ),
    ]
